AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Secrets Manager for Memecoin Sniping Solution

Resources:
  SolanaWalletSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /memecoin-sniping/solana-wallet-private-key
      Description: Private key for the Solana wallet used by the Trader agent.
      SecretString: '{"privateKey": "YOUR_SOLANA_PRIVATE_KEY"}'
      Tags:
        - Key: Project
          Value: MemecoinSniping
        - Key: Component
          Value: SolanaWalletSecret

  HeliusApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /memecoin-sniping/helius-api-key
      Description: API Key for Helius service.
      SecretString: '{"apiKey": "YOUR_HELIUS_API_KEY"}'
      Tags:
        - Key: Project
          Value: MemecoinSniping
        - Key: Component
          Value: HeliusApiKeySecret

  TwitterApiSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /memecoin-sniping/twitter-api-secrets
      Description: API keys and tokens for Twitter API.
      SecretString: '{"consumerKey": "YOUR_CONSUMER_KEY", "consumerSecret": "YOUR_CONSUMER_SECRET", "accessToken": "YOUR_ACCESS_TOKEN", "accessTokenSecret": "YOUR_ACCESS_TOKEN_SECRET"}'
      Tags:
        - Key: Project
          Value: MemecoinSniping
        - Key: Component
          Value: TwitterApiSecrets

  TelegramApiSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /memecoin-sniping/telegram-api-secret
      Description: API token for Telegram Bot API.
      SecretString: '{"botToken": "YOUR_TELEGRAM_BOT_TOKEN"}'
      Tags:
        - Key: Project
          Value: MemecoinSniping
        - Key: Component
          Value: TelegramApiSecret

Outputs:
  SolanaWalletSecretArn:
    Description: ARN of the Solana Wallet Private Key Secret
    Value: !Ref SolanaWalletSecret
    Export:
      Name: SolanaWalletSecretArn

  HeliusApiKeySecretArn:
    Description: ARN of the Helius API Key Secret
    Value: !Ref HeliusApiKeySecret
    Export:
      Name: HeliusApiKeySecretArn

  TwitterApiSecretsArn:
    Description: ARN of the Twitter API Secrets
    Value: !Ref TwitterApiSecrets
    Export:
      Name: TwitterApiSecretsArn

  TelegramApiSecretArn:
    Description: ARN of the Telegram API Secret
    Value: !Ref TelegramApiSecret
    Export:
      Name: TelegramApiSecretArn


