AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Monitoring and Alerts for Memecoin Sniping Solution

Parameters:
  AlertEmail:
    Type: String
    Description: Email address for alerts
    Default: admin@example.com

Resources:
  # CloudWatch Alarms for Lambda Functions
  DiscovererErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Discoverer-Errors
      AlarmDescription: Alert when Discoverer Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingDiscoverer
      AlarmActions:
        - !Ref AlertTopic

  AnalyzerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Analyzer-Errors
      AlarmDescription: Alert when Analyzer Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingAnalyzer
      AlarmActions:
        - !Ref AlertTopic

  TraderErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Trader-Errors
      AlarmDescription: Alert when Trader Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingTrader
      AlarmActions:
        - !Ref AlertTopic

  OptimizerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Optimizer-Errors
      AlarmDescription: Alert when Optimizer Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingOptimizer
      AlarmActions:
        - !Ref AlertTopic

  ModelTrainerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-ModelTrainer-Errors
      AlarmDescription: Alert when Model Trainer Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingModelTrainer
      AlarmActions:
        - !Ref AlertTopic

  ModelDeployerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-ModelDeployer-Errors
      AlarmDescription: Alert when Model Deployer Lambda has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: MemecoinSnipingModelDeployer
      AlarmActions:
        - !Ref AlertTopic

  # Custom Metrics for Trading Performance
  DrawdownAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-High-Drawdown
      AlarmDescription: Alert when drawdown exceeds 15%
      MetricName: Drawdown
      Namespace: MemecoinSniping/Trading
      Statistic: Maximum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 15
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic

  # SQS Queue Depth Alarms
  DiscovererQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Discoverer-Queue-Depth
      AlarmDescription: Alert when Discoverer queue has too many messages
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !ImportValue DiscovererQueueName
      AlarmActions:
        - !Ref AlertTopic

  AnalyzerQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: MemecoinSniping-Analyzer-Queue-Depth
      AlarmDescription: Alert when Analyzer queue has too many messages
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !ImportValue AnalyzerQueueName
      AlarmActions:
        - !Ref AlertTopic

  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MemecoinSnipingAlerts
      DisplayName: Memecoin Sniping Alerts

  AlertTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref AlertTopic
      Endpoint: !Ref AlertEmail

  # CloudWatch Dashboard
  TradingDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: MemecoinSniping-Trading-Dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingDiscoverer" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Discoverer Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingAnalyzer" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Analyzer Metrics"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingTrader" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Trader Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "MemecoinSniping/Trading", "TotalPnL" ],
                  [ ".", "WinRate" ],
                  [ ".", "Drawdown" ]
                ],
                "period": 3600,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Trading Performance"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/SQS", "ApproximateNumberOfVisibleMessages", "QueueName", !ImportValue DiscovererQueueName ],
                  [ ".", ".", ".", !ImportValue AnalyzerQueueName ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Queue Depths"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 18,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingExecutor" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Executor Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 18,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingEtlProcessor" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "ETL Processor Metrics"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 24,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingModelTrainer" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Model Trainer Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 24,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingModelDeployer" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Model Deployer Metrics"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 30,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "MemecoinSnipingOptimizer" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Duration", ".", "." ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Optimizer Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 30,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/SageMaker", "Invocations", "EndpointName", "memecoin-optimizer-endpoint" ],
                  [ ".", "Invocations4XX", ".", "." ],
                  [ ".", "Invocations5XX", ".", "." ],
                  [ ".", "ModelLatency", ".", "." ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "SageMaker Endpoint Metrics"
              }
            }
          ]
        }

Outputs:
  AlertTopicArn:
    Description: ARN of the SNS Topic for alerts
    Value: !Ref AlertTopic

  DashboardURL:
    Description: URL of the CloudWatch Dashboard
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${TradingDashboard}"


